package epm;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author Jia Li
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    TOOLTIP_NEW_EPORTFOLIO,
    TOOLTIP_LOAD_EPORTFOLIO,
    TOOLTIP_SAVE_EPORTFOLIO,
    TOOLTIP_SAVE_AS_EPORTFOLIO,
    TOOLTIP_EXPORT_EPORTFOLIO,
    TOOLTIP_EDIT_EPORTFOLIO,
    TOOLTIP_VIEW_EPORTFOLIO,
    TOOLTIP_EXIT,
    TOOLTIP_ADD_PAGE,
    TOOLTIP_REMOVE_PAGE,
    TOOLTIP_EDIT_COMPONENT,
    TOOLTIP_ADD_TEXT,
    TOOLTIP_ADD_VIDEO,
    TOOLTIP_ADD_IMAGE,
    TOOLTIP_ADD_SLIDESHOW,
    TOOLTIP_ADD_HYPERLINK,
    TOOLTIP_EDIT_HYPERLINK,
    TOOLTIP_EDIT_FONT,
    TOOLTIP_REMOVE_COMPONENT,
    
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_SLIDE_SHOW_TITLE,
    BUTTON_OKAY,
    SAVE_TEXT,
          
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    NO_PAGES,
    NO_EPORTFOLIO,
    MISSING_IMAGE,
    MISSING_IMAGE_TITLE,
    FAILED_EPORTFOLIO_CREATED,
    FAILED_EPORTFOLIO_LOAD,
    FAILED_EPORTFOLIO_SAVE,
    FAILED_EPORTFOLIO_EXIT,
    FAILED_EPORTFOLIO_TITLE,
    ERROR_DATA_FILE_LOADING, 
    ERROR_PROPERTIES_FILE_LOADING,
    
    /*
     THESE ARE FOR LANGUAGE-DEPENDENT SUCCESS POP-UPS,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN A SUCCESS HAS OCCURED */
    EPORTFOLIO_CREATED,
    EPORTFOLIO_CREATED_TITLE,
}
